# Package definition for buf

package_name: buf
github_repo: bufbuild/buf
artifact_format: tar.gz
description: "The best way of working with Protocol Buffers."
license: Apache-2.0
# buf tar contains buf/bin/buf nested, needs bundle handling
binary_path: "buf"
bundle: true

# Build for all Debian suites and all supported architectures.
